### ISSUE TITLE
Add support for cucumber 3.0

### ISSUE THREAD

**Issue by danoliv** [cucumber/cucumber-jvm-scala#10]
cucumber 3.0 brings interesting features for scala users (and finally drops XStream).

**Comment by mpkorstanje** [comment]
As you may or may not have noticed. The [core team has decided to drop support for the lesser used languages](
https://cucumber.io/blog/2018/05/19/cucumber-jvm-languages-support). If you're willing and able to take up this task or any part of it, fee free to do so.

**Comment by danoliv** [comment]
Thanks for your answer, I will have a look at the code and perhaps send a pull request. Just to clarify if someone will do it are you going to build an official release or nor?

**Comment by mpkorstanje** [comment]
I doubt I'll be able to find the time to do so. However the barrier to entry to the project is quite low. After your first PR is merged you'll automatically be given sufficient rights to the repo. After that you can setup CI/CD. The only thing you won't have access to straight away are the signing keys needed to make a release. But I can help with that.

**Comment by GeReinhart** [comment]
I guess, the pull request #12 just merged close this issue. Thanks to @glib-briia ! We were about to do the same as we work with scala and cucumber.
