### ISSUE TITLE
Cucumber Scala final output shows 0 failures even when a scenario fails

### ISSUE THREAD

**Issue by rhande-mdsol** [cucumber/cucumber-jvm-scala#102]
I have a cucumber test suite which has some tests 

I run the tests using command 

    sbt "testOnly <cucumber_class_name>"
And one of the cucumber tests fail an assertion and console shows 

`Failed scenarios:`
`classpath:features/my_cucumber_scenario.feature:31# <my test description>`

19 Scenarios (1 failed, 18 passed)
88 Steps (1 failed, 87 passed)sts 214s
3m18.224s

But in the end the console shows 

`Total 80, Failed 0, Errors 0, Passed 80`

Since one of the tests failed, in the final output it should have shown
`Failed 1` (Or something like that). But it is showing all passed instead due to which my build on travis is not failing.

 
How to solve this problem ? Is there a solution in cucumber ? 

My dependencies are 

"io.cucumber" % "cucumber-core" % "5.7.0",
"io.cucumber" % "cucumber-junit" % "5.7.0"
"io.cucumber" %% "cucumber-scala" % "5.7.0"

**Comment by gaeljw** [comment]
Hello @rhande-mdsol ,

Could it be that you have multiple scenarios with the same name, or Scenario Outlines?

If so, this is is a known issue in sbt-junit interface: 
https://github.com/sbt/junit-interface/issues/84. See also #22

**Comment by mpkorstanje** [comment]
Might be worth adding a work around to detect if sbt-junit is used and act accordingly.

**Comment by mpkorstanje** [comment]
Or ensure the names provided to the JUnit Description are always unique. That way sbt will also be able to handle identical features, scenarios, examples, ect.

**Comment by mpkorstanje** [comment]
Would either of you mind checking if https://github.com/cucumber/cucumber-jvm/pull/2045 solves the problem.

**Comment by rhande-mdsol** [comment]
> Hello @rhande-mdsol ,
> 
> Could it be that you have multiple scenarios with the same name, or Scenario Outlines?
> 
> If so, this is is a known issue in sbt-junit interface:
> [sbt/junit-interface#84](https://github.com/sbt/junit-interface/issues/84). See also #22

**Comment by rhande-mdsol** [comment]
Sorry Closed by mistake.

**Comment by rhande-mdsol** [comment]
@mpkorstanje I am using

"io.cucumber" % "cucumber-core" % "5.7.0",
"io.cucumber" % "cucumber-junit" % "5.7.0"
"io.cucumber" %% "cucumber-scala" % "5.7.0"

So it is cucumber scala. Your code seems to be Java code.  Can I use it ?

**Comment by gaeljw** [comment]
@rhande-mdsol Cucumber Scala is using Cucumber JVM which is the foundation for various Cucumber libraries targeting the JVM.

In this case, it's the project `cucumber-junit` that you could try to build on your own with the PR mentioned by @mpkorstanje and use in your project.

I will also try the PR on my side but probably later today.

@rhande-mdsol Do you confirm that your case is multiple scenarios with the same name in the same file, or using Scenario Outlines ?

**Comment by rhande-mdsol** [comment]
> @rhande-mdsol Cucumber Scala is using Cucumber JVM which is the foundation for various Cucumber libraries targeting the JVM.
> 
> In this case, it's the project `cucumber-junit` that you could try to build on your own with the PR mentioned by @mpkorstanje and use in your project.
> 
> I will also try the PR on my side but probably later today.
> 
> @rhande-mdsol Do you confirm that your case is multiple scenarios with the same name in the same file, or using Scenario Outlines ?

Hi @gaeljw ,

Yes, this problem happens when I have a `Scenario Outline` and then have a table like structure in  `Examples:` section. For me 3rd example actually failed, but final result showed all tests passed.


I also tried failing a scenario without an outline (i.e. `Scenario:`) in this case final result shows failures properly.

Thanks

**Comment by gaeljw** [comment]
Thanks for confirming.

https://github.com/cucumber/cucumber-jvm/pull/2045 should fix the issue then.
You just have to wait a bit for the next `cucumber-junit` release (you'll have to update to 6.x but the upgrade from 5.x to 6.x is pretty easy).

**Comment by rhande-mdsol** [comment]
Thanks for fixing the problem. Now final result shows failure when there is a failure in scenario outline.

**Comment by ejaoua** [comment]
Hi @rhande-mdsol ,
can you please share what was the plugin and/or correct syntax that you used to run one test of Cucumber :
sbt "testOnly <cucumber_class_name>". 
I tried the following but it didn't work out `sbt "testOnly *classpath:features/folder1/endpoint.feature`
Thanks.

**Comment by gaeljw** [comment]
@ejaoua you might want to take it to Slack to discuss these kind of things, or open a new issue/discussion at least.

Short answer: I don't think that's possible this way. You have to run `testOnly SomeClass` where `SomeClass` targets only some features file.
