### ISSUE TITLE
Cucumber 6.2.2 not listing all the failed scenarios at the end of tests run

### ISSUE THREAD

**Issue by rhande-mdsol** [cucumber/cucumber-jvm-scala#105]
**Describe the bug**
When one or more scenarios failed, we don't get a list of failed scenarios:
like 

`Failed scenarios:`
`classpath:features/myfile.feature:12# <my_scenario_description 1>`
`classpath:features/myfile.feature:15# <my_scenario_description 2>`

**To Reproduce**
Run feature file with a failing test. 

**Expected behavior**
Failed scenarios should be listed in the end, as it helps developers to identify quickly especially when there is a huge number of tests.
** cucumber Version being used**

  **"io.cucumber" % "cucumber-core" % "6.2.2"**
  **"io.cucumber" % "cucumber-junit" % "6.2.2"**
  **"io.cucumber" %% "cucumber-scala" % "6.2.2"**

The same thing was working when the cucumber version was `5.7.0`.

I am not sure if this change was introduced on purpose in version 6 or above. Please suggest if this can be achieved by any configuration change (such as `CucumberOptions`).

Thanks in advance.

**Comment by mpkorstanje** [comment]
When using JUnit you have to use `@CucumberOptions(plugin = {"summary"})` to make Cucumber report on failures. However I would expect your JUnit integration to report on the failures. Cucumber no longer reports failures by default because these reports would inter-leaf with the output of other tooling.

**Comment by rhande-mdsol** [comment]
Thanks for the helo @mpkorstanje . This `plugin = {"summary"}`  helps to address the particular problem. I am closing the issue
