### ISSUE TITLE
Be ready for Scala 3

### ISSUE THREAD

**Issue by gaeljw** [cucumber/cucumber-jvm-scala#139]
Scala 3.x is on its way (http://dotty.epfl.ch/blog/2020/09/21/naming-schema-change.html).

Even though users of Scala 3.x projects should be able to use Cucumber Scala compiled with Scala 2.x, it would be nice if Cucumber Scala was cross compiled to Scala 3.x as well.

That being said, there is for now no support of Scala 3 with the Scala Maven plugin (https://github.com/davidB/scala-maven-plugin/issues/393), thus if we want to move forward we have two options:
- contribute to the Scala Maven plugin
- move away from Maven and use `sbt` instead

I would tend to vote for the 2nd option, as AFAIK the majority of Scala libraries are built with `sbt` which offers way more convenience especially from cross-builiding projects to multiple versions of Scala. It could also help Scala developers contribute more easily with a known project structure instead of the "home-made" Maven structure we have for now.

:question:  _But_ as of today we rely on Maven also for releasing the project and I don't know if we want to keep it like this or not.

:bulb:  **An intermediate step could be to still use Maven for the top level commands (build, release...) but delegate to `sbt` the actual build**. This is something I've seen working quite well using the Exec Maven plugin.

Any thought on the topic appreciated! @mpkorstanje maybe :wink:

**Comment by mpkorstanje** [comment]
Maven is not required to build the project. However to upload to the OSS signed maven artifacts must be provided. There are ways to do this with sbt.

https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html

**Comment by gaeljw** [comment]
Indeed, I was wondering if for consistency with Cucumber JVM it would make more sense to keep the release process much closer and thus keep Maven for the deployment to repos.

Or as long as the `Makefile` takes care of the necessary step, it doesn't really matter?

**Comment by mpkorstanje** [comment]
Yup. Aslong as `make release` does everything in docker it doesn't matter. And I guess committing and tagging the change in version numbers to git.

**Comment by gaeljw** [comment]
Issues with Scala 3.0.0-M1:
- https://github.com/lampepfl/dotty/issues/10325

**Comment by gaeljw** [comment]
Mainly closed by #186
