### ISSUE TITLE
Scala 2.13

### ISSUE THREAD

**Issue by lewismj** [cucumber/cucumber-jvm-scala#16]
Any plans to support Scala 2.13?

**Comment by mpkorstanje** [comment]
This project is almost entirely developed by volunteers. Would you be willing to provide a branch that adds support for Scala 2.13?

**Comment by lewismj** [comment]
Ok, will take a look - hopefully later today.

**Comment by lewismj** [comment]
Raised a PR, hopefully this works.

**Comment by glib-briia** [comment]
PR merged #18
