### ISSUE TITLE
@Transform does not work in Scala DSL

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm-scala#2]
From https://github.com/cucumber/cucumber-jvm/issues/922
> @Transform in Scala DSL does not work and I have to define my own class using XStreamConverter to make it work. 
> 
> ``` scala
> 
> class MyClassConverter extends Transformer[MyClass] {
>  //implementation of Transform function
> }
> 
> def given(@Transform(classOf[MyClassConverter]) c: MyClass) {
>     //Some Code
> }
> 
> Given("""^I have my (.*) as part of my given $""".stripMargin) { given _ }
> ```
> 
> This does not pick `MyClassConverter` as a converter for `MyClass`
>

**Comment by glib-briia** [comment]
This is now fixed by introducing TypeRegistryConfigurer https://cucumber.io/blog/2018/05/19/announcing-cucumber-jvm-3-0-0

Fixed in cucumber-scala v.4.1.0
