### ISSUE TITLE
New maintainers wanted!

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm-scala#21]
We haven't had the time, or expertise to keep to the Scala implementation up to date. So we're looking for one or more new maintainers. The tasks are roughly:

- Code! Scratch your own itch
- Keep dependencies uptodate
- Respond to GitHub issues/PRs in a timely manner
- Keep the CHANGELOG uptodate
- Make releases (Create git tags, update CHANGELOG)
- Keep the documentation uptodate
- Make the code habitable for new users and contributors
- Keep the CI running

If you are interested - comment on this issue!

**Comment by gaeljw** [comment]
I could be interested as in my company we make massive usage of both Scala and BDD, thus we rely a lot on this project.
I'll see If I can get some time to work on this.
