### ISSUE TITLE
Errors not reported with duplicated scenarios names

### ISSUE THREAD

**Issue by gaeljw** [cucumber/cucumber-jvm-scala#22]
**Context**

I believe the issue might not be related to cucumber-jvm-scala because I only reproduce it when using sbt as build tool rather than maven but I feel it's better to enter an issue here in case someone have the issue in the future.
We'll link to another issue in another project if the fix is not part of this project.

**Issue**

Given we have two scenarios with the same name (`Scenario: a scenario name`) in the same file
When I run `sbt test`
And one of them is failing but not the other
Then the result is "SUCCESS" instead of "ERROR"

![image](https://user-images.githubusercontent.com/18280708/79210217-cc60e700-7e44-11ea-8dbf-fd38b9e7b63f.png)

It seems that only the result of the first test is considered, thus depending on order of tests the result is different.

**Reproduction**

Clone https://github.com/gaeljw/cucumber-jvm-scala-issue-duplicate-scenarios/tree/master and run `sbt test`

**What about Maven?**

As mentionned, I cannot reproduce with the same project (Scala) using Maven (https://github.com/gaeljw/cucumber-jvm-scala-issue-duplicate-scenarios/tree/maven)

**Comment by mpkorstanje** [comment]
Sounds like there is a bug in the integration between SBT and  JUnit. I'm guessing that SBT assumes that tests are class+method based and thus always unique. You can probebly reproduce this using only JUnit by creating a `ParentRunner` implementation that has two identically named tests.

**Comment by gaeljw** [comment]
Yes, you're absolutely right :+1: 

I tracked down the issue and it comes to the integration between sbt and JUnit.
I will open an issue on sbt side.
We could workaround this somehow by assigning a unique `description` to the `TestNotifier` in 
[JUnitReporter.java#L90](https://github.com/cucumber/cucumber-jvm/blob/master/junit/src/main/java/io/cucumber/junit/JUnitReporter.java#L90) in cucumber-junit but I guess it doesn't make much sense if this works fine in Maven/Java world.

**Comment by gaeljw** [comment]
Relates to https://github.com/sbt/junit-interface/issues/84.

I will close this one.

**Comment by mpkorstanje** [comment]
Looks like you may have to do some convincing here:

https://github.com/sbt/junit-interface/pull/83#issuecomment-580529538

Pretty sure we are within specs.
