### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-jvm-scala#266]
**What's the problem you've observed? 🤔**

Releases are not automated, this means we have to run the build scripts on maintainers' local machines, and also means that credentials for releases have to be copied onto those machines.

**Do you have a proposal for making it better? 🦄**

Implement a GitHub action, based on a protected `release/vX.Y.Z` branch as we have done in other repos (see https://github.com/cucumber/common/issues/1688)

**Comment by gaeljw** [comment]
Let me know if you need any help @mattwynne ;)

**Comment by gaeljw** [comment]
Closed by #269 (and several additional commits :sweat_smile: )
