### ISSUE TITLE
GPG updates

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm-scala#276]
I'm not sure if the `gpg.sh` script is used anymore after #269 was merged.

If it isn't - maybe delete it?
If it is used, please beware that I've renamed `GPG_SIGNING_KEY_PASSPHRASE` to `GPG_PASSPHRASE` in the `secrets` repo on keybase.

**Comment by gaeljw** [comment]
Thanks for the notice.

The custom `gpg.sh` is still used but there's actually no reason for that. It was a workaround for old version of the `sbt-sonatype` plugin.
The test project at https://github.com/cucumber/action-publish-sbt doesn't use it and it publish successfully.

I will remove it.

Though the secrets are now defined in GitHub secrets right? There is no sync with Keybase, isn't it?

**Comment by gaeljw** [comment]
Actually even though it's still used, I'm not even sure it has any effect because nothing provides the environment variable anymore and the gpg stuff are done as part of the cucumber-action-sbt.

Anyway, one more reason to get rid of it!

**Comment by mattwynne** [comment]
We noticed it because we've been adding some scripts in the keybase repo to automatically set up the secrets in GitHub. So keybase will still be the source of truth, but we aim to remove all the coupling _towards_ it from our development environments.

**Comment by gaeljw** [comment]
Sorry for the delay, I did remove the custom gpg script and ran a patch release few minutes ago with success. :white_check_mark:
