### ISSUE TITLE
UndefinedDataTableTypeException with Boolean

### ISSUE THREAD

**Issue by gaeljw** [cucumber/cucumber-jvm-scala#322]
### 👓 What did you see?

From comment from @ckorakidis at https://github.com/cucumber/cucumber-jvm-scala/issues/50#issuecomment-1242808230

> Can't use DataTable: `io.cucumber.datatable.UndefinedDataTableTypeException: Can't convert DataTable to Map<java.lang.String, boolean>`
I use it like: `dataTable.asScalaMap[String, Boolean]` in StepDefinitions which extends EN and have imported `io.cucumber.scala.Implicits._`

### ✅ What did you expect to see?

Cucumber should be able to convert to a map with `Boolean` (Scala or Java) values.

### 📦 Which tool/library version are you using?

Cucumber Scala 8.9.0
Cucumber core 7.7.0

#### With Scala Booleans

```gherkin
Scenario: As Map of boolean
    Given the following table as Scala Map with boolean
      | row1 | true  |
      | row2 |       |
      | row3 | false |
```

```scala
  Given("the following table as Scala Map with boolean") { (table: DataTable) =>
    val data: Map[String, Option[Boolean]] =
      table.asScalaMap[String, Boolean]
    val expected = Map(
      "row1" -> Some(true),
      "row2" -> None,
      "row3" -> Some(false)
    )
    assert(data == expected)
  }
```

The error:
```
io.cucumber.datatable.UndefinedDataTableTypeException: Can't convert DataTable to Map<java.lang.String, boolean>.
[error] Please review these problems:
[error] 
[error]  - There was no table entry transformer registered for boolean.
[error]    Please consider registering a table entry transformer.
[error] 
[error]  - There was no table cell transformer registered for boolean.
[error]    Please consider registering a table cell transformer.
[error] 
[error]  - There was no default table cell transformer registered to transform boolean.
[error]    Please consider registering a default table cell transformer.
[error] 
```

#### With Java Boolean

Replacing `Boolean` with `java.lang.Boolean` does not help, the same error is still present:

```
io.cucumber.datatable.UndefinedDataTableTypeException: Can't convert DataTable to Map<java.lang.String, java.lang.Boolean>.
[error] Please review these problems:
[error] 
[error]  - There was no table entry transformer registered for java.lang.Boolean.
[error]    Please consider registering a table entry transformer.
[error] 
[error]  - There was no table cell transformer registered for java.lang.Boolean.
[error]    Please consider registering a table cell transformer.
[error] 
[error]  - There was no default table cell transformer registered to transform java.lang.Boolean.
[error]    Please consider registering a default table cell transformer.
[error] 
```

### 📚 Any additional context?

N/A

**Comment by gaeljw** [comment]
Thanks for raising the issue @ckorakidis, next time do not hesitate to open a fresh issue rather than commenting on an already fixed one.

I can reproduce the issue but while I thought it would be related to Scala's `Boolean`, it also happens with Java's `java.lang.Boolean`. I will thus forward the issue to Cucumber JVM team.
Though to be fair I'm not sure they will consider this as an issue.

In the meantime, the easier workaround would be to parse as a `Map[String, String]` and then convert values to boolean:
```scala
    val data: Map[String, Option[Boolean]] =
      table
        .asScalaMap[String, String]
        .map { case (k, v) => k -> v.map(_.toBoolean) }
```

**Comment by gaeljw** [comment]
See https://github.com/cucumber/cucumber-jvm/issues/2611 for the JVM issue

**Comment by ckorakidis** [comment]
Thanks @gaeljw, thought I was missing something.

**Comment by ckorakidis** [comment]
Workaround for the time being: `dataTable.asScalaMap[String, String].map(r => r._1 -> r._2.contains("true"))`
