### ISSUE TITLE
Maven central has a bunch of different repos for `cucumber-scala`

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/cucumber-jvm-scala#5]
Not sure what's going on here, but I see a bunch of different repos for `cucumber-scala`: https://search.maven.org/#search%7Cga%7C1%7Ccucumber-scala

There are several listed as "Latest version" 2.0.1 or 1.2.5, but with ArtifactId listed as `cucumber-scala_2.9`, `cucumber-scala_2.10`, `cucumber-scala_2.11`, `cucumber-scala_2.12`

**Comment by mlvandijk** [comment]
Added a Maven central badge to the README, like we have for cucumber-jvm - it currently lists version as "unknown" probably due to the fact that there are different repos listed.

**Comment by brasmusson** [comment]
From the cucumber-scala project three versions are build for scala v2.10, v2.11 and v2.12 respectively. The Maven central badge should probably point to the artifact id `cucumber-scala-aggreagator` as it (the `pom.xml` in the scala directory) act as parent for all the different cucumber-scala versions.

**Comment by mlvandijk** [comment]
Thnx @brasmusson - fixed :)

**Comment by mpkorstanje** [comment]
I think there should be 3 badges. The aggregator project can't be used by anyone.

**Comment by mpkorstanje** [comment]
I've changed the badge and the dependency section to point to the `scala_2.12` version. It is the latest and hopefully most relevant.
